version: "3.3"

services:
  server:
    image: gitea/gitea:latest
#    restart: always
    volumes:
      - $GITEA_DATADIR:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000"
      - "2222"
    environment:
      - VIRTUAL_HOST=git.emamaker.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=git.emamaker.com
      - LETSENCRYPT_EMAIL=emamaker0@gmail.com
    networks:
      - default

networks:
  default:
    external:
      name: $SERVER_DOCKER_NETWORKNAME
